[project]
name = "Automatic generation of Pydantic models with all the fields set to optional."
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pydantic==1.10",
]
