"""Auto-generated by generate_partial_models.py. """

from pydantic import Field
from typing import Literal
from models import BasePartial, UNSET, Unset
from typing import Union



class UserPartial(BasePartial):
    """Autogenerated partial model by generate_partial_models.py.

    You can still add your custom methods here, they won't be overwritten by
    the generated code.
    """

    first_name: Union[str, Literal['Alessandro'], Unset] = Field(default=UNSET)
    last_name: Union[str, Unset] = Field(default=UNSET)


    def say_hi(self):
        """I'm a custom method.

        Try to add/remove a field in the `User` model and re-generate the partial
        models. I'll wait here :)
        """
        raise NotImplementedError()


