"""Auto-generated partial model from generate_partial_models.py. """

from models import BasePartial, UNSET, Unset
from pydantic import Field
from typing import Literal
from typing import Union



class UserPartial(BasePartial):
    """Autogenerated from generate_partial_models.py.

    You can still add your custom methods here, they won't be overwritten by
    the generated code.
    """

    first_name: Union[str, Literal['Alessandro'], Unset] = Field(default=UNSET, required=False)
    last_name: Union[str, Unset] = Field(default=UNSET, required=False)

    def say_hi(self):
        """I'm a custom method.

        Try to add/remove a field in the `User` model and re-generate the partial
        models. I'll wait here :)
        """
        raise NotImplementedError()


